services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notafacil_app
    restart: unless-stopped
    ports:
      - "3000:3000"  # Mapeo puerto host:contenedor
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - notafacil-network
    volumes:
      - ./logs:/app/logs

networks:
  notafacil-network:
    driver: bridge
